// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED FPV testbench generated by util/design/secded_gen.py

module prim_secded_hamming_72_64_tb (
  input               clk_i,
  input               rst_ni,
  input        [63:0] data_i,
  output logic [63:0] data_o,
  output logic [71:0] encoded_o,
  output logic [7:0] syndrome_o,
  output logic [1:0]  err_o,
  input        [71:0] error_inject_i
);
  import prim_secded_pkg::*;

  // Instantiate secded encoder and decoder based on parameters.
  `include "prim_secded_inc.svh"

  `SECDED_INST_ENC(SecdedHamming, 64, prim_secded_hamming_72_64_enc, data_i, encoded_o)

  `SECDED_INST_DEC(SecdedHamming, 64, prim_secded_hamming_72_64_dec, encoded_o ^ error_inject_i,
                    data_o, syndrome_o, err_o)

endmodule : prim_secded_hamming_72_64_tb
