// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package otp_ctrl_reg_pkg;

  // Param list
  parameter int NumSramKeyReqSlots = 4;
  parameter int OtpDepth = 2048;
  parameter int OtpWidth = 2;
  parameter int OtpSizeWidth = 2;
  parameter int OtpByteAddrWidth = 12;
  parameter int NumErrorEntries = 28;
  parameter int NumDaiWords = 2;
  parameter int NumDigestWords = 2;
  parameter int NumSwCfgWindowWords = 1024;
  parameter int NumPart = 26;
  parameter int NumPartUnbuf = 18;
  parameter int NumPartBuf = 8;
  parameter int VendorTestOffset = 0;
  parameter int VendorTestSize = 64;
  parameter int ScratchOffset = 0;
  parameter int ScratchSize = 56;
  parameter int VendorTestDigestOffset = 56;
  parameter int VendorTestDigestSize = 8;
  parameter int CreatorSwCfgOffset = 64;
  parameter int CreatorSwCfgSize = 352;
  parameter int CreatorSwCfgAstCfgOffset = 64;
  parameter int CreatorSwCfgAstCfgSize = 156;
  parameter int CreatorSwCfgAstInitSizeOffset = 220;
  parameter int CreatorSwCfgAstInitSizeSize = 4;
  parameter int CreatorSwCfgSigverifySpxEnOffset = 224;
  parameter int CreatorSwCfgSigverifySpxEnSize = 4;
  parameter int CreatorSwCfgFlashDataDefaultCfgOffset = 228;
  parameter int CreatorSwCfgFlashDataDefaultCfgSize = 4;
  parameter int CreatorSwCfgFlashInfoBootDataCfgOffset = 232;
  parameter int CreatorSwCfgFlashInfoBootDataCfgSize = 4;
  parameter int CreatorSwCfgFlashHwInfoCfgOverrideOffset = 236;
  parameter int CreatorSwCfgFlashHwInfoCfgOverrideSize = 4;
  parameter int CreatorSwCfgRngEnOffset = 240;
  parameter int CreatorSwCfgRngEnSize = 4;
  parameter int CreatorSwCfgJitterEnOffset = 244;
  parameter int CreatorSwCfgJitterEnSize = 4;
  parameter int CreatorSwCfgRetRamResetMaskOffset = 248;
  parameter int CreatorSwCfgRetRamResetMaskSize = 4;
  parameter int CreatorSwCfgManufStateOffset = 252;
  parameter int CreatorSwCfgManufStateSize = 4;
  parameter int CreatorSwCfgRomExecEnOffset = 256;
  parameter int CreatorSwCfgRomExecEnSize = 4;
  parameter int CreatorSwCfgCpuctrlOffset = 260;
  parameter int CreatorSwCfgCpuctrlSize = 4;
  parameter int CreatorSwCfgRngRepcntThresholdsOffset = 264;
  parameter int CreatorSwCfgRngRepcntThresholdsSize = 4;
  parameter int CreatorSwCfgRngRepcntsThresholdsOffset = 268;
  parameter int CreatorSwCfgRngRepcntsThresholdsSize = 4;
  parameter int CreatorSwCfgRngAdaptpHiThresholdsOffset = 272;
  parameter int CreatorSwCfgRngAdaptpHiThresholdsSize = 4;
  parameter int CreatorSwCfgRngAdaptpLoThresholdsOffset = 276;
  parameter int CreatorSwCfgRngAdaptpLoThresholdsSize = 4;
  parameter int CreatorSwCfgRngBucketThresholdsOffset = 280;
  parameter int CreatorSwCfgRngBucketThresholdsSize = 4;
  parameter int CreatorSwCfgRngMarkovHiThresholdsOffset = 284;
  parameter int CreatorSwCfgRngMarkovHiThresholdsSize = 4;
  parameter int CreatorSwCfgRngMarkovLoThresholdsOffset = 288;
  parameter int CreatorSwCfgRngMarkovLoThresholdsSize = 4;
  parameter int CreatorSwCfgRngExthtHiThresholdsOffset = 292;
  parameter int CreatorSwCfgRngExthtHiThresholdsSize = 4;
  parameter int CreatorSwCfgRngExthtLoThresholdsOffset = 296;
  parameter int CreatorSwCfgRngExthtLoThresholdsSize = 4;
  parameter int CreatorSwCfgRngAlertThresholdOffset = 300;
  parameter int CreatorSwCfgRngAlertThresholdSize = 4;
  parameter int CreatorSwCfgRngHealthConfigDigestOffset = 304;
  parameter int CreatorSwCfgRngHealthConfigDigestSize = 4;
  parameter int CreatorSwCfgSramKeyRenewAndInitEnOffset = 308;
  parameter int CreatorSwCfgSramKeyRenewAndInitEnSize = 4;
  parameter int CreatorSwCfgDigestOffset = 408;
  parameter int CreatorSwCfgDigestSize = 8;
  parameter int OwnerSwCfgOffset = 416;
  parameter int OwnerSwCfgSize = 656;
  parameter int OwnerSwCfgRomErrorReportingOffset = 416;
  parameter int OwnerSwCfgRomErrorReportingSize = 4;
  parameter int OwnerSwCfgRomBootstrapDisOffset = 420;
  parameter int OwnerSwCfgRomBootstrapDisSize = 4;
  parameter int OwnerSwCfgRomAlertClassEnOffset = 424;
  parameter int OwnerSwCfgRomAlertClassEnSize = 4;
  parameter int OwnerSwCfgRomAlertEscalationOffset = 428;
  parameter int OwnerSwCfgRomAlertEscalationSize = 4;
  parameter int OwnerSwCfgRomAlertClassificationOffset = 432;
  parameter int OwnerSwCfgRomAlertClassificationSize = 320;
  parameter int OwnerSwCfgRomLocalAlertClassificationOffset = 752;
  parameter int OwnerSwCfgRomLocalAlertClassificationSize = 64;
  parameter int OwnerSwCfgRomAlertAccumThreshOffset = 816;
  parameter int OwnerSwCfgRomAlertAccumThreshSize = 16;
  parameter int OwnerSwCfgRomAlertTimeoutCyclesOffset = 832;
  parameter int OwnerSwCfgRomAlertTimeoutCyclesSize = 16;
  parameter int OwnerSwCfgRomAlertPhaseCyclesOffset = 848;
  parameter int OwnerSwCfgRomAlertPhaseCyclesSize = 64;
  parameter int OwnerSwCfgRomAlertDigestProdOffset = 912;
  parameter int OwnerSwCfgRomAlertDigestProdSize = 4;
  parameter int OwnerSwCfgRomAlertDigestProdEndOffset = 916;
  parameter int OwnerSwCfgRomAlertDigestProdEndSize = 4;
  parameter int OwnerSwCfgRomAlertDigestDevOffset = 920;
  parameter int OwnerSwCfgRomAlertDigestDevSize = 4;
  parameter int OwnerSwCfgRomAlertDigestRmaOffset = 924;
  parameter int OwnerSwCfgRomAlertDigestRmaSize = 4;
  parameter int OwnerSwCfgRomWatchdogBiteThresholdCyclesOffset = 928;
  parameter int OwnerSwCfgRomWatchdogBiteThresholdCyclesSize = 4;
  parameter int OwnerSwCfgRomKeymgrOtpMeasEnOffset = 932;
  parameter int OwnerSwCfgRomKeymgrOtpMeasEnSize = 4;
  parameter int OwnerSwCfgManufStateOffset = 936;
  parameter int OwnerSwCfgManufStateSize = 4;
  parameter int OwnerSwCfgRomRstmgrInfoEnOffset = 940;
  parameter int OwnerSwCfgRomRstmgrInfoEnSize = 4;
  parameter int OwnerSwCfgRomSensorCtrlAlertCfgOffset = 944;
  parameter int OwnerSwCfgRomSensorCtrlAlertCfgSize = 12;
  parameter int OwnerSwCfgRomSramReadbackEnOffset = 956;
  parameter int OwnerSwCfgRomSramReadbackEnSize = 4;
  parameter int OwnerSwCfgRomFlashEccExcHandlerEnOffset = 960;
  parameter int OwnerSwCfgRomFlashEccExcHandlerEnSize = 4;
  parameter int OwnerSwCfgDigestOffset = 1064;
  parameter int OwnerSwCfgDigestSize = 8;
  parameter int OwnershipSlotStateOffset = 1072;
  parameter int OwnershipSlotStateSize = 8;
  parameter int OwnershipSlotStateZerOffset = 1072;
  parameter int OwnershipSlotStateZerSize = 8;
  parameter int RotCreatorIdentityOffset = 1080;
  parameter int RotCreatorIdentitySize = 800;
  parameter int RotCreatorIdentityCertOffset = 1080;
  parameter int RotCreatorIdentityCertSize = 768;
  parameter int RotCreatorIdentityCertCmacOffset = 1848;
  parameter int RotCreatorIdentityCertCmacSize = 16;
  parameter int RotCreatorIdentityDigestOffset = 1864;
  parameter int RotCreatorIdentityDigestSize = 8;
  parameter int RotCreatorIdentityZerOffset = 1872;
  parameter int RotCreatorIdentityZerSize = 8;
  parameter int RotOwnerAuthSlot0Offset = 1880;
  parameter int RotOwnerAuthSlot0Size = 120;
  parameter int RotOwnerAuthSlot0FirmwareCodesignKeyTypeOffset = 1880;
  parameter int RotOwnerAuthSlot0FirmwareCodesignKeyTypeSize = 4;
  parameter int RotOwnerAuthSlot0FirmwareCodesignEcdsaKeyOffset = 1884;
  parameter int RotOwnerAuthSlot0FirmwareCodesignEcdsaKeySize = 64;
  parameter int RotOwnerAuthSlot0FirmwareCodesignSpxKeyOffset = 1948;
  parameter int RotOwnerAuthSlot0FirmwareCodesignSpxKeySize = 32;
  parameter int RotOwnerAuthSlot0FirmwareCodesignSpxKeyConfigOffset = 1980;
  parameter int RotOwnerAuthSlot0FirmwareCodesignSpxKeyConfigSize = 4;
  parameter int RotOwnerAuthSlot0DigestOffset = 1984;
  parameter int RotOwnerAuthSlot0DigestSize = 8;
  parameter int RotOwnerAuthSlot0ZerOffset = 1992;
  parameter int RotOwnerAuthSlot0ZerSize = 8;
  parameter int RotOwnerAuthSlot1Offset = 2000;
  parameter int RotOwnerAuthSlot1Size = 120;
  parameter int RotOwnerAuthSlot1FirmwareCodesignKeyTypeOffset = 2000;
  parameter int RotOwnerAuthSlot1FirmwareCodesignKeyTypeSize = 4;
  parameter int RotOwnerAuthSlot1FirmwareCodesignEcdsaKeyOffset = 2004;
  parameter int RotOwnerAuthSlot1FirmwareCodesignEcdsaKeySize = 64;
  parameter int RotOwnerAuthSlot1FirmwareCodesignSpxKeyOffset = 2068;
  parameter int RotOwnerAuthSlot1FirmwareCodesignSpxKeySize = 32;
  parameter int RotOwnerAuthSlot1FirmwareCodesignSpxKeyConfigOffset = 2100;
  parameter int RotOwnerAuthSlot1FirmwareCodesignSpxKeyConfigSize = 4;
  parameter int RotOwnerAuthSlot1DigestOffset = 2104;
  parameter int RotOwnerAuthSlot1DigestSize = 8;
  parameter int RotOwnerAuthSlot1ZerOffset = 2112;
  parameter int RotOwnerAuthSlot1ZerSize = 8;
  parameter int RotOwnerAuthSlot2Offset = 2120;
  parameter int RotOwnerAuthSlot2Size = 120;
  parameter int RotOwnerAuthSlot2FirmwareCodesignKeyTypeOffset = 2120;
  parameter int RotOwnerAuthSlot2FirmwareCodesignKeyTypeSize = 4;
  parameter int RotOwnerAuthSlot2FirmwareCodesignEcdsaKeyOffset = 2124;
  parameter int RotOwnerAuthSlot2FirmwareCodesignEcdsaKeySize = 64;
  parameter int RotOwnerAuthSlot2FirmwareCodesignSpxKeyOffset = 2188;
  parameter int RotOwnerAuthSlot2FirmwareCodesignSpxKeySize = 32;
  parameter int RotOwnerAuthSlot2FirmwareCodesignSpxKeyConfigOffset = 2220;
  parameter int RotOwnerAuthSlot2FirmwareCodesignSpxKeyConfigSize = 4;
  parameter int RotOwnerAuthSlot2DigestOffset = 2224;
  parameter int RotOwnerAuthSlot2DigestSize = 8;
  parameter int RotOwnerAuthSlot2ZerOffset = 2232;
  parameter int RotOwnerAuthSlot2ZerSize = 8;
  parameter int RotOwnerAuthSlot3Offset = 2240;
  parameter int RotOwnerAuthSlot3Size = 120;
  parameter int RotOwnerAuthSlot3FirmwareCodesignKeyTypeOffset = 2240;
  parameter int RotOwnerAuthSlot3FirmwareCodesignKeyTypeSize = 4;
  parameter int RotOwnerAuthSlot3FirmwareCodesignEcdsaKeyOffset = 2244;
  parameter int RotOwnerAuthSlot3FirmwareCodesignEcdsaKeySize = 64;
  parameter int RotOwnerAuthSlot3FirmwareCodesignSpxKeyOffset = 2308;
  parameter int RotOwnerAuthSlot3FirmwareCodesignSpxKeySize = 32;
  parameter int RotOwnerAuthSlot3FirmwareCodesignSpxKeyConfigOffset = 2340;
  parameter int RotOwnerAuthSlot3FirmwareCodesignSpxKeyConfigSize = 4;
  parameter int RotOwnerAuthSlot3DigestOffset = 2344;
  parameter int RotOwnerAuthSlot3DigestSize = 8;
  parameter int RotOwnerAuthSlot3ZerOffset = 2352;
  parameter int RotOwnerAuthSlot3ZerSize = 8;
  parameter int RotOwnerAuthSlot0StateOffset = 2360;
  parameter int RotOwnerAuthSlot0StateSize = 24;
  parameter int RotOwnerAuthSlot0StateFirmwareCodesignEcdsaKeyStateOffset = 2360;
  parameter int RotOwnerAuthSlot0StateFirmwareCodesignEcdsaKeyStateSize = 4;
  parameter int RotOwnerAuthSlot0StateFirmwareCodesignSpxKeyStateOffset = 2364;
  parameter int RotOwnerAuthSlot0StateFirmwareCodesignSpxKeyStateSize = 4;
  parameter int RotOwnerAuthSlot0StateRom1PatchEcdsaKeyStateOffset = 2368;
  parameter int RotOwnerAuthSlot0StateRom1PatchEcdsaKeyStateSize = 4;
  parameter int RotOwnerAuthSlot0StateRom1PatchSpxKeyStateOffset = 2372;
  parameter int RotOwnerAuthSlot0StateRom1PatchSpxKeyStateSize = 4;
  parameter int RotOwnerAuthSlot0StateDigestOffset = 2376;
  parameter int RotOwnerAuthSlot0StateDigestSize = 8;
  parameter int RotOwnerAuthSlot1StateOffset = 2384;
  parameter int RotOwnerAuthSlot1StateSize = 24;
  parameter int RotOwnerAuthSlot1StateFirmwareCodesignEcdsaKeyStateOffset = 2384;
  parameter int RotOwnerAuthSlot1StateFirmwareCodesignEcdsaKeyStateSize = 4;
  parameter int RotOwnerAuthSlot1StateFirmwareCodesignSpxKeyStateOffset = 2388;
  parameter int RotOwnerAuthSlot1StateFirmwareCodesignSpxKeyStateSize = 4;
  parameter int RotOwnerAuthSlot1StateRom1PatchEcdsaKeyStateOffset = 2392;
  parameter int RotOwnerAuthSlot1StateRom1PatchEcdsaKeyStateSize = 4;
  parameter int RotOwnerAuthSlot1StateRom1PatchSpxKeyStateOffset = 2396;
  parameter int RotOwnerAuthSlot1StateRom1PatchSpxKeyStateSize = 4;
  parameter int RotOwnerAuthSlot1StateDigestOffset = 2400;
  parameter int RotOwnerAuthSlot1StateDigestSize = 8;
  parameter int RotOwnerAuthSlot2StateOffset = 2408;
  parameter int RotOwnerAuthSlot2StateSize = 16;
  parameter int RotOwnerAuthSlot2StateFirmwareCodesignEcdsaKeyStateOffset = 2408;
  parameter int RotOwnerAuthSlot2StateFirmwareCodesignEcdsaKeyStateSize = 4;
  parameter int RotOwnerAuthSlot2StateFirmwareCodesignSpxKeyStateOffset = 2412;
  parameter int RotOwnerAuthSlot2StateFirmwareCodesignSpxKeyStateSize = 4;
  parameter int RotOwnerAuthSlot2StateDigestOffset = 2416;
  parameter int RotOwnerAuthSlot2StateDigestSize = 8;
  parameter int RotOwnerAuthSlot3StateOffset = 2424;
  parameter int RotOwnerAuthSlot3StateSize = 16;
  parameter int RotOwnerAuthSlot3StateFirmwareCodesignEcdsaKeyStateOffset = 2424;
  parameter int RotOwnerAuthSlot3StateFirmwareCodesignEcdsaKeyStateSize = 4;
  parameter int RotOwnerAuthSlot3StateFirmwareCodesignSpxKeyStateOffset = 2428;
  parameter int RotOwnerAuthSlot3StateFirmwareCodesignSpxKeyStateSize = 4;
  parameter int RotOwnerAuthSlot3StateDigestOffset = 2432;
  parameter int RotOwnerAuthSlot3StateDigestSize = 8;
  parameter int ExtNvmOffset = 2440;
  parameter int ExtNvmSize = 1032;
  parameter int ExtNvmAntireplayFreshnessCntOffset = 2440;
  parameter int ExtNvmAntireplayFreshnessCntSize = 1024;
  parameter int ExtNvmZerOffset = 3464;
  parameter int ExtNvmZerSize = 8;
  parameter int RomPatchOffset = 3472;
  parameter int RomPatchSize = 16;
  parameter int RomPatchDigestOffset = 3472;
  parameter int RomPatchDigestSize = 8;
  parameter int RomPatchZerOffset = 3480;
  parameter int RomPatchZerSize = 8;
  parameter int SocFusesCpOffset = 3488;
  parameter int SocFusesCpSize = 8;
  parameter int SocFusesCpDigestOffset = 3488;
  parameter int SocFusesCpDigestSize = 8;
  parameter int SocFusesFtOffset = 3496;
  parameter int SocFusesFtSize = 8;
  parameter int SocFusesFtDigestOffset = 3496;
  parameter int SocFusesFtDigestSize = 8;
  parameter int ScratchFusesOffset = 3504;
  parameter int ScratchFusesSize = 104;
  parameter int ScratchFusesDataOffset = 3504;
  parameter int ScratchFusesDataSize = 96;
  parameter int ScratchFusesZerOffset = 3600;
  parameter int ScratchFusesZerSize = 8;
  parameter int HwCfg0Offset = 3608;
  parameter int HwCfg0Size = 40;
  parameter int DeviceIdOffset = 3608;
  parameter int DeviceIdSize = 32;
  parameter int HwCfg0DigestOffset = 3640;
  parameter int HwCfg0DigestSize = 8;
  parameter int HwCfg1Offset = 3648;
  parameter int HwCfg1Size = 16;
  parameter int EnSramIfetchOffset = 3648;
  parameter int EnSramIfetchSize = 1;
  parameter int EnCsrngSwAppReadOffset = 3649;
  parameter int EnCsrngSwAppReadSize = 1;
  parameter int DisRvDmLateDebugOffset = 3650;
  parameter int DisRvDmLateDebugSize = 1;
  parameter int HwCfg1DigestOffset = 3656;
  parameter int HwCfg1DigestSize = 8;
  parameter int HwCfg2Offset = 3664;
  parameter int HwCfg2Size = 48;
  parameter int ManufStateOffset = 3664;
  parameter int ManufStateSize = 32;
  parameter int HwCfg2DigestOffset = 3696;
  parameter int HwCfg2DigestSize = 8;
  parameter int HwCfg2ZerOffset = 3704;
  parameter int HwCfg2ZerSize = 8;
  parameter int Secret0Offset = 3712;
  parameter int Secret0Size = 40;
  parameter int TestUnlockTokenOffset = 3712;
  parameter int TestUnlockTokenSize = 16;
  parameter int TestExitTokenOffset = 3728;
  parameter int TestExitTokenSize = 16;
  parameter int Secret0DigestOffset = 3744;
  parameter int Secret0DigestSize = 8;
  parameter int Secret1Offset = 3752;
  parameter int Secret1Size = 88;
  parameter int FlashAddrKeySeedOffset = 3752;
  parameter int FlashAddrKeySeedSize = 32;
  parameter int FlashDataKeySeedOffset = 3784;
  parameter int FlashDataKeySeedSize = 32;
  parameter int SramDataKeySeedOffset = 3816;
  parameter int SramDataKeySeedSize = 16;
  parameter int Secret1DigestOffset = 3832;
  parameter int Secret1DigestSize = 8;
  parameter int Secret2Offset = 3840;
  parameter int Secret2Size = 120;
  parameter int RmaTokenOffset = 3840;
  parameter int RmaTokenSize = 16;
  parameter int CreatorRootKeyShare0Offset = 3856;
  parameter int CreatorRootKeyShare0Size = 32;
  parameter int CreatorRootKeyShare1Offset = 3888;
  parameter int CreatorRootKeyShare1Size = 32;
  parameter int CreatorSeedOffset = 3920;
  parameter int CreatorSeedSize = 32;
  parameter int Secret2DigestOffset = 3952;
  parameter int Secret2DigestSize = 8;
  parameter int Secret3Offset = 3960;
  parameter int Secret3Size = 48;
  parameter int OwnerSeedOffset = 3960;
  parameter int OwnerSeedSize = 32;
  parameter int Secret3DigestOffset = 3992;
  parameter int Secret3DigestSize = 8;
  parameter int Secret3ZerOffset = 4000;
  parameter int Secret3ZerSize = 8;
  parameter int LifeCycleOffset = 4008;
  parameter int LifeCycleSize = 88;
  parameter int LcTransitionCntOffset = 4008;
  parameter int LcTransitionCntSize = 48;
  parameter int LcStateOffset = 4056;
  parameter int LcStateSize = 40;
  parameter int NumAlerts = 5;

  // Address widths within the block
  parameter int CoreAw = 13;

  // Number of registers for every interface
  parameter int NumRegsCore = 109;

  // Alert indices
  typedef enum int {
    AlertFatalMacroErrorIdx = 0,
    AlertFatalCheckErrorIdx = 1,
    AlertFatalBusIntegErrorIdx = 2,
    AlertFatalPrimOtpAlertIdx = 3,
    AlertRecovPrimOtpAlertIdx = 4
  } otp_ctrl_alert_idx_t;

  ///////////////////////////////////////////////
  // Typedefs for registers for core interface //
  ///////////////////////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } otp_error;
    struct packed {
      logic        q;
    } otp_operation_done;
  } otp_ctrl_reg2hw_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } otp_error;
    struct packed {
      logic        q;
    } otp_operation_done;
  } otp_ctrl_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } otp_error;
    struct packed {
      logic        q;
      logic        qe;
    } otp_operation_done;
  } otp_ctrl_reg2hw_intr_test_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } recov_prim_otp_alert;
    struct packed {
      logic        q;
      logic        qe;
    } fatal_prim_otp_alert;
    struct packed {
      logic        q;
      logic        qe;
    } fatal_bus_integ_error;
    struct packed {
      logic        q;
      logic        qe;
    } fatal_check_error;
    struct packed {
      logic        q;
      logic        qe;
    } fatal_macro_error;
  } otp_ctrl_reg2hw_alert_test_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } otp_ctrl_reg2hw_direct_access_regwen_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } zeroize;
    struct packed {
      logic        q;
      logic        qe;
    } digest;
    struct packed {
      logic        q;
      logic        qe;
    } wr;
    struct packed {
      logic        q;
      logic        qe;
    } rd;
  } otp_ctrl_reg2hw_direct_access_cmd_reg_t;

  typedef struct packed {
    logic [11:0] q;
  } otp_ctrl_reg2hw_direct_access_address_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } otp_ctrl_reg2hw_direct_access_wdata_mreg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } consistency;
    struct packed {
      logic        q;
      logic        qe;
    } integrity;
  } otp_ctrl_reg2hw_check_trigger_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } otp_ctrl_reg2hw_check_timeout_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } otp_ctrl_reg2hw_integrity_check_period_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } otp_ctrl_reg2hw_consistency_check_period_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_vendor_test_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_creator_sw_cfg_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_owner_sw_cfg_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_ownership_slot_state_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_creator_identity_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot0_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot1_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot2_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot3_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot0_state_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot1_state_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot2_state_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rot_owner_auth_slot3_state_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_ext_nvm_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_rom_patch_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_soc_fuses_cp_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_soc_fuses_ft_read_lock_reg_t;

  typedef struct packed {
    logic        q;
  } otp_ctrl_reg2hw_scratch_fuses_read_lock_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } otp_error;
    struct packed {
      logic        d;
      logic        de;
    } otp_operation_done;
  } otp_ctrl_hw2reg_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } check_pending;
    struct packed {
      logic        d;
    } dai_idle;
    struct packed {
      logic        d;
    } bus_integ_error;
    struct packed {
      logic        d;
    } key_deriv_fsm_error;
    struct packed {
      logic        d;
    } scrambling_fsm_error;
    struct packed {
      logic        d;
    } lfsr_fsm_error;
    struct packed {
      logic        d;
    } timeout_error;
    struct packed {
      logic        d;
    } lci_error;
    struct packed {
      logic        d;
    } dai_error;
    struct packed {
      logic        d;
    } partition_error;
  } otp_ctrl_hw2reg_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } life_cycle_error;
    struct packed {
      logic        d;
    } secret3_error;
    struct packed {
      logic        d;
    } secret2_error;
    struct packed {
      logic        d;
    } secret1_error;
    struct packed {
      logic        d;
    } secret0_error;
    struct packed {
      logic        d;
    } hw_cfg2_error;
    struct packed {
      logic        d;
    } hw_cfg1_error;
    struct packed {
      logic        d;
    } hw_cfg0_error;
    struct packed {
      logic        d;
    } scratch_fuses_error;
    struct packed {
      logic        d;
    } soc_fuses_ft_error;
    struct packed {
      logic        d;
    } soc_fuses_cp_error;
    struct packed {
      logic        d;
    } rom_patch_error;
    struct packed {
      logic        d;
    } ext_nvm_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot3_state_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot2_state_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot1_state_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot0_state_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot3_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot2_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot1_error;
    struct packed {
      logic        d;
    } rot_owner_auth_slot0_error;
    struct packed {
      logic        d;
    } rot_creator_identity_error;
    struct packed {
      logic        d;
    } ownership_slot_state_error;
    struct packed {
      logic        d;
    } owner_sw_cfg_error;
    struct packed {
      logic        d;
    } creator_sw_cfg_error;
    struct packed {
      logic        d;
    } vendor_test_error;
  } otp_ctrl_hw2reg_partition_status_0_reg_t;

  typedef struct packed {
    logic [2:0]  d;
  } otp_ctrl_hw2reg_err_code_mreg_t;

  typedef struct packed {
    logic        d;
  } otp_ctrl_hw2reg_direct_access_regwen_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_direct_access_rdata_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_vendor_test_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_creator_sw_cfg_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_owner_sw_cfg_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_creator_identity_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot0_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot1_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot2_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot3_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot0_state_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot1_state_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot2_state_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rot_owner_auth_slot3_state_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_rom_patch_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_soc_fuses_cp_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_soc_fuses_ft_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_hw_cfg0_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_hw_cfg1_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_hw_cfg2_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_secret0_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_secret1_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_secret2_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } otp_ctrl_hw2reg_secret3_digest_mreg_t;

  // Register -> HW type for core interface
  typedef struct packed {
    otp_ctrl_reg2hw_intr_state_reg_t intr_state; // [221:220]
    otp_ctrl_reg2hw_intr_enable_reg_t intr_enable; // [219:218]
    otp_ctrl_reg2hw_intr_test_reg_t intr_test; // [217:214]
    otp_ctrl_reg2hw_alert_test_reg_t alert_test; // [213:204]
    otp_ctrl_reg2hw_direct_access_regwen_reg_t direct_access_regwen; // [203:202]
    otp_ctrl_reg2hw_direct_access_cmd_reg_t direct_access_cmd; // [201:194]
    otp_ctrl_reg2hw_direct_access_address_reg_t direct_access_address; // [193:182]
    otp_ctrl_reg2hw_direct_access_wdata_mreg_t [1:0] direct_access_wdata; // [181:118]
    otp_ctrl_reg2hw_check_trigger_reg_t check_trigger; // [117:114]
    otp_ctrl_reg2hw_check_timeout_reg_t check_timeout; // [113:82]
    otp_ctrl_reg2hw_integrity_check_period_reg_t integrity_check_period; // [81:50]
    otp_ctrl_reg2hw_consistency_check_period_reg_t consistency_check_period; // [49:18]
    otp_ctrl_reg2hw_vendor_test_read_lock_reg_t vendor_test_read_lock; // [17:17]
    otp_ctrl_reg2hw_creator_sw_cfg_read_lock_reg_t creator_sw_cfg_read_lock; // [16:16]
    otp_ctrl_reg2hw_owner_sw_cfg_read_lock_reg_t owner_sw_cfg_read_lock; // [15:15]
    otp_ctrl_reg2hw_ownership_slot_state_read_lock_reg_t ownership_slot_state_read_lock; // [14:14]
    otp_ctrl_reg2hw_rot_creator_identity_read_lock_reg_t rot_creator_identity_read_lock; // [13:13]
    otp_ctrl_reg2hw_rot_owner_auth_slot0_read_lock_reg_t rot_owner_auth_slot0_read_lock; // [12:12]
    otp_ctrl_reg2hw_rot_owner_auth_slot1_read_lock_reg_t rot_owner_auth_slot1_read_lock; // [11:11]
    otp_ctrl_reg2hw_rot_owner_auth_slot2_read_lock_reg_t rot_owner_auth_slot2_read_lock; // [10:10]
    otp_ctrl_reg2hw_rot_owner_auth_slot3_read_lock_reg_t rot_owner_auth_slot3_read_lock; // [9:9]
    otp_ctrl_reg2hw_rot_owner_auth_slot0_state_read_lock_reg_t
        rot_owner_auth_slot0_state_read_lock; // [8:8]
    otp_ctrl_reg2hw_rot_owner_auth_slot1_state_read_lock_reg_t
        rot_owner_auth_slot1_state_read_lock; // [7:7]
    otp_ctrl_reg2hw_rot_owner_auth_slot2_state_read_lock_reg_t
        rot_owner_auth_slot2_state_read_lock; // [6:6]
    otp_ctrl_reg2hw_rot_owner_auth_slot3_state_read_lock_reg_t
        rot_owner_auth_slot3_state_read_lock; // [5:5]
    otp_ctrl_reg2hw_ext_nvm_read_lock_reg_t ext_nvm_read_lock; // [4:4]
    otp_ctrl_reg2hw_rom_patch_read_lock_reg_t rom_patch_read_lock; // [3:3]
    otp_ctrl_reg2hw_soc_fuses_cp_read_lock_reg_t soc_fuses_cp_read_lock; // [2:2]
    otp_ctrl_reg2hw_soc_fuses_ft_read_lock_reg_t soc_fuses_ft_read_lock; // [1:1]
    otp_ctrl_reg2hw_scratch_fuses_read_lock_reg_t scratch_fuses_read_lock; // [0:0]
  } otp_ctrl_core_reg2hw_t;

  // HW -> register type for core interface
  typedef struct packed {
    otp_ctrl_hw2reg_intr_state_reg_t intr_state; // [1596:1593]
    otp_ctrl_hw2reg_status_reg_t status; // [1592:1583]
    otp_ctrl_hw2reg_partition_status_0_reg_t partition_status_0; // [1582:1557]
    otp_ctrl_hw2reg_err_code_mreg_t [27:0] err_code; // [1556:1473]
    otp_ctrl_hw2reg_direct_access_regwen_reg_t direct_access_regwen; // [1472:1472]
    otp_ctrl_hw2reg_direct_access_rdata_mreg_t [1:0] direct_access_rdata; // [1471:1408]
    otp_ctrl_hw2reg_vendor_test_digest_mreg_t [1:0] vendor_test_digest; // [1407:1344]
    otp_ctrl_hw2reg_creator_sw_cfg_digest_mreg_t [1:0] creator_sw_cfg_digest; // [1343:1280]
    otp_ctrl_hw2reg_owner_sw_cfg_digest_mreg_t [1:0] owner_sw_cfg_digest; // [1279:1216]
    otp_ctrl_hw2reg_rot_creator_identity_digest_mreg_t [1:0]
        rot_creator_identity_digest; // [1215:1152]
    otp_ctrl_hw2reg_rot_owner_auth_slot0_digest_mreg_t [1:0]
        rot_owner_auth_slot0_digest; // [1151:1088]
    otp_ctrl_hw2reg_rot_owner_auth_slot1_digest_mreg_t [1:0]
        rot_owner_auth_slot1_digest; // [1087:1024]
    otp_ctrl_hw2reg_rot_owner_auth_slot2_digest_mreg_t [1:0]
        rot_owner_auth_slot2_digest; // [1023:960]
    otp_ctrl_hw2reg_rot_owner_auth_slot3_digest_mreg_t [1:0]
        rot_owner_auth_slot3_digest; // [959:896]
    otp_ctrl_hw2reg_rot_owner_auth_slot0_state_digest_mreg_t [1:0]
        rot_owner_auth_slot0_state_digest; // [895:832]
    otp_ctrl_hw2reg_rot_owner_auth_slot1_state_digest_mreg_t [1:0]
        rot_owner_auth_slot1_state_digest; // [831:768]
    otp_ctrl_hw2reg_rot_owner_auth_slot2_state_digest_mreg_t [1:0]
        rot_owner_auth_slot2_state_digest; // [767:704]
    otp_ctrl_hw2reg_rot_owner_auth_slot3_state_digest_mreg_t [1:0]
        rot_owner_auth_slot3_state_digest; // [703:640]
    otp_ctrl_hw2reg_rom_patch_digest_mreg_t [1:0] rom_patch_digest; // [639:576]
    otp_ctrl_hw2reg_soc_fuses_cp_digest_mreg_t [1:0] soc_fuses_cp_digest; // [575:512]
    otp_ctrl_hw2reg_soc_fuses_ft_digest_mreg_t [1:0] soc_fuses_ft_digest; // [511:448]
    otp_ctrl_hw2reg_hw_cfg0_digest_mreg_t [1:0] hw_cfg0_digest; // [447:384]
    otp_ctrl_hw2reg_hw_cfg1_digest_mreg_t [1:0] hw_cfg1_digest; // [383:320]
    otp_ctrl_hw2reg_hw_cfg2_digest_mreg_t [1:0] hw_cfg2_digest; // [319:256]
    otp_ctrl_hw2reg_secret0_digest_mreg_t [1:0] secret0_digest; // [255:192]
    otp_ctrl_hw2reg_secret1_digest_mreg_t [1:0] secret1_digest; // [191:128]
    otp_ctrl_hw2reg_secret2_digest_mreg_t [1:0] secret2_digest; // [127:64]
    otp_ctrl_hw2reg_secret3_digest_mreg_t [1:0] secret3_digest; // [63:0]
  } otp_ctrl_core_hw2reg_t;

  // Register offsets for core interface
  parameter logic [CoreAw-1:0] OTP_CTRL_INTR_STATE_OFFSET = 13'h 0;
  parameter logic [CoreAw-1:0] OTP_CTRL_INTR_ENABLE_OFFSET = 13'h 4;
  parameter logic [CoreAw-1:0] OTP_CTRL_INTR_TEST_OFFSET = 13'h 8;
  parameter logic [CoreAw-1:0] OTP_CTRL_ALERT_TEST_OFFSET = 13'h c;
  parameter logic [CoreAw-1:0] OTP_CTRL_STATUS_OFFSET = 13'h 10;
  parameter logic [CoreAw-1:0] OTP_CTRL_PARTITION_STATUS_0_OFFSET = 13'h 14;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_0_OFFSET = 13'h 18;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_1_OFFSET = 13'h 1c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_2_OFFSET = 13'h 20;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_3_OFFSET = 13'h 24;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_4_OFFSET = 13'h 28;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_5_OFFSET = 13'h 2c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_6_OFFSET = 13'h 30;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_7_OFFSET = 13'h 34;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_8_OFFSET = 13'h 38;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_9_OFFSET = 13'h 3c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_10_OFFSET = 13'h 40;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_11_OFFSET = 13'h 44;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_12_OFFSET = 13'h 48;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_13_OFFSET = 13'h 4c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_14_OFFSET = 13'h 50;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_15_OFFSET = 13'h 54;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_16_OFFSET = 13'h 58;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_17_OFFSET = 13'h 5c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_18_OFFSET = 13'h 60;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_19_OFFSET = 13'h 64;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_20_OFFSET = 13'h 68;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_21_OFFSET = 13'h 6c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_22_OFFSET = 13'h 70;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_23_OFFSET = 13'h 74;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_24_OFFSET = 13'h 78;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_25_OFFSET = 13'h 7c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_26_OFFSET = 13'h 80;
  parameter logic [CoreAw-1:0] OTP_CTRL_ERR_CODE_27_OFFSET = 13'h 84;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_REGWEN_OFFSET = 13'h 88;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_CMD_OFFSET = 13'h 8c;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_ADDRESS_OFFSET = 13'h 90;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_WDATA_0_OFFSET = 13'h 94;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_WDATA_1_OFFSET = 13'h 98;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_RDATA_0_OFFSET = 13'h 9c;
  parameter logic [CoreAw-1:0] OTP_CTRL_DIRECT_ACCESS_RDATA_1_OFFSET = 13'h a0;
  parameter logic [CoreAw-1:0] OTP_CTRL_CHECK_TRIGGER_REGWEN_OFFSET = 13'h a4;
  parameter logic [CoreAw-1:0] OTP_CTRL_CHECK_TRIGGER_OFFSET = 13'h a8;
  parameter logic [CoreAw-1:0] OTP_CTRL_CHECK_REGWEN_OFFSET = 13'h ac;
  parameter logic [CoreAw-1:0] OTP_CTRL_CHECK_TIMEOUT_OFFSET = 13'h b0;
  parameter logic [CoreAw-1:0] OTP_CTRL_INTEGRITY_CHECK_PERIOD_OFFSET = 13'h b4;
  parameter logic [CoreAw-1:0] OTP_CTRL_CONSISTENCY_CHECK_PERIOD_OFFSET = 13'h b8;
  parameter logic [CoreAw-1:0] OTP_CTRL_VENDOR_TEST_READ_LOCK_OFFSET = 13'h bc;
  parameter logic [CoreAw-1:0] OTP_CTRL_CREATOR_SW_CFG_READ_LOCK_OFFSET = 13'h c0;
  parameter logic [CoreAw-1:0] OTP_CTRL_OWNER_SW_CFG_READ_LOCK_OFFSET = 13'h c4;
  parameter logic [CoreAw-1:0] OTP_CTRL_OWNERSHIP_SLOT_STATE_READ_LOCK_OFFSET = 13'h c8;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_CREATOR_IDENTITY_READ_LOCK_OFFSET = 13'h cc;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_READ_LOCK_OFFSET = 13'h d0;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_READ_LOCK_OFFSET = 13'h d4;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_READ_LOCK_OFFSET = 13'h d8;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_READ_LOCK_OFFSET = 13'h dc;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_READ_LOCK_OFFSET = 13'h e0;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_READ_LOCK_OFFSET = 13'h e4;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_READ_LOCK_OFFSET = 13'h e8;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_READ_LOCK_OFFSET = 13'h ec;
  parameter logic [CoreAw-1:0] OTP_CTRL_EXT_NVM_READ_LOCK_OFFSET = 13'h f0;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROM_PATCH_READ_LOCK_OFFSET = 13'h f4;
  parameter logic [CoreAw-1:0] OTP_CTRL_SOC_FUSES_CP_READ_LOCK_OFFSET = 13'h f8;
  parameter logic [CoreAw-1:0] OTP_CTRL_SOC_FUSES_FT_READ_LOCK_OFFSET = 13'h fc;
  parameter logic [CoreAw-1:0] OTP_CTRL_SCRATCH_FUSES_READ_LOCK_OFFSET = 13'h 100;
  parameter logic [CoreAw-1:0] OTP_CTRL_VENDOR_TEST_DIGEST_0_OFFSET = 13'h 104;
  parameter logic [CoreAw-1:0] OTP_CTRL_VENDOR_TEST_DIGEST_1_OFFSET = 13'h 108;
  parameter logic [CoreAw-1:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_0_OFFSET = 13'h 10c;
  parameter logic [CoreAw-1:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_1_OFFSET = 13'h 110;
  parameter logic [CoreAw-1:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_0_OFFSET = 13'h 114;
  parameter logic [CoreAw-1:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_1_OFFSET = 13'h 118;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_0_OFFSET = 13'h 11c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_1_OFFSET = 13'h 120;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0_OFFSET = 13'h 124;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1_OFFSET = 13'h 128;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0_OFFSET = 13'h 12c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1_OFFSET = 13'h 130;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_0_OFFSET = 13'h 134;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_1_OFFSET = 13'h 138;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_0_OFFSET = 13'h 13c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_1_OFFSET = 13'h 140;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_0_OFFSET = 13'h 144;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_1_OFFSET = 13'h 148;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_0_OFFSET = 13'h 14c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_1_OFFSET = 13'h 150;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_0_OFFSET = 13'h 154;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_1_OFFSET = 13'h 158;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_0_OFFSET = 13'h 15c;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_1_OFFSET = 13'h 160;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROM_PATCH_DIGEST_0_OFFSET = 13'h 164;
  parameter logic [CoreAw-1:0] OTP_CTRL_ROM_PATCH_DIGEST_1_OFFSET = 13'h 168;
  parameter logic [CoreAw-1:0] OTP_CTRL_SOC_FUSES_CP_DIGEST_0_OFFSET = 13'h 16c;
  parameter logic [CoreAw-1:0] OTP_CTRL_SOC_FUSES_CP_DIGEST_1_OFFSET = 13'h 170;
  parameter logic [CoreAw-1:0] OTP_CTRL_SOC_FUSES_FT_DIGEST_0_OFFSET = 13'h 174;
  parameter logic [CoreAw-1:0] OTP_CTRL_SOC_FUSES_FT_DIGEST_1_OFFSET = 13'h 178;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG0_DIGEST_0_OFFSET = 13'h 17c;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG0_DIGEST_1_OFFSET = 13'h 180;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG1_DIGEST_0_OFFSET = 13'h 184;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG1_DIGEST_1_OFFSET = 13'h 188;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG2_DIGEST_0_OFFSET = 13'h 18c;
  parameter logic [CoreAw-1:0] OTP_CTRL_HW_CFG2_DIGEST_1_OFFSET = 13'h 190;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET0_DIGEST_0_OFFSET = 13'h 194;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET0_DIGEST_1_OFFSET = 13'h 198;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET1_DIGEST_0_OFFSET = 13'h 19c;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET1_DIGEST_1_OFFSET = 13'h 1a0;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET2_DIGEST_0_OFFSET = 13'h 1a4;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET2_DIGEST_1_OFFSET = 13'h 1a8;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET3_DIGEST_0_OFFSET = 13'h 1ac;
  parameter logic [CoreAw-1:0] OTP_CTRL_SECRET3_DIGEST_1_OFFSET = 13'h 1b0;

  // Reset values for hwext registers and their fields for core interface
  parameter logic [1:0] OTP_CTRL_INTR_TEST_RESVAL = 2'h 0;
  parameter logic [0:0] OTP_CTRL_INTR_TEST_OTP_OPERATION_DONE_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_INTR_TEST_OTP_ERROR_RESVAL = 1'h 0;
  parameter logic [4:0] OTP_CTRL_ALERT_TEST_RESVAL = 5'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_FATAL_MACRO_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_FATAL_CHECK_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_FATAL_BUS_INTEG_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_FATAL_PRIM_OTP_ALERT_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_ALERT_TEST_RECOV_PRIM_OTP_ALERT_RESVAL = 1'h 0;
  parameter logic [9:0] OTP_CTRL_STATUS_RESVAL = 10'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_PARTITION_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_DAI_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_LCI_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_TIMEOUT_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_LFSR_FSM_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_SCRAMBLING_FSM_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_KEY_DERIV_FSM_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_BUS_INTEG_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_DAI_IDLE_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_STATUS_CHECK_PENDING_RESVAL = 1'h 0;
  parameter logic [25:0] OTP_CTRL_PARTITION_STATUS_0_RESVAL = 26'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_VENDOR_TEST_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_CREATOR_SW_CFG_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_OWNER_SW_CFG_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_OWNERSHIP_SLOT_STATE_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROT_CREATOR_IDENTITY_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROT_OWNER_AUTH_SLOT0_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROT_OWNER_AUTH_SLOT1_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROT_OWNER_AUTH_SLOT2_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROT_OWNER_AUTH_SLOT3_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROT_OWNER_AUTH_SLOT0_STATE_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROT_OWNER_AUTH_SLOT1_STATE_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROT_OWNER_AUTH_SLOT2_STATE_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROT_OWNER_AUTH_SLOT3_STATE_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_EXT_NVM_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_ROM_PATCH_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_SOC_FUSES_CP_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_SOC_FUSES_FT_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_SCRATCH_FUSES_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_HW_CFG0_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_HW_CFG1_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_HW_CFG2_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_SECRET0_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_SECRET1_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_SECRET2_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_SECRET3_ERROR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_PARTITION_STATUS_0_LIFE_CYCLE_ERROR_RESVAL = 1'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_0_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_0_ERR_CODE_0_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_1_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_1_ERR_CODE_1_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_2_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_2_ERR_CODE_2_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_3_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_3_ERR_CODE_3_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_4_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_4_ERR_CODE_4_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_5_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_5_ERR_CODE_5_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_6_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_6_ERR_CODE_6_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_7_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_7_ERR_CODE_7_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_8_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_8_ERR_CODE_8_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_9_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_9_ERR_CODE_9_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_10_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_10_ERR_CODE_10_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_11_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_11_ERR_CODE_11_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_12_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_12_ERR_CODE_12_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_13_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_13_ERR_CODE_13_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_14_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_14_ERR_CODE_14_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_15_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_15_ERR_CODE_15_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_16_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_16_ERR_CODE_16_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_17_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_17_ERR_CODE_17_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_18_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_18_ERR_CODE_18_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_19_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_19_ERR_CODE_19_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_20_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_20_ERR_CODE_20_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_21_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_21_ERR_CODE_21_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_22_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_22_ERR_CODE_22_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_23_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_23_ERR_CODE_23_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_24_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_24_ERR_CODE_24_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_25_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_25_ERR_CODE_25_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_26_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_26_ERR_CODE_26_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_27_RESVAL = 3'h 0;
  parameter logic [2:0] OTP_CTRL_ERR_CODE_27_ERR_CODE_27_RESVAL = 3'h 0;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_REGWEN_RESVAL = 1'h 1;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_REGWEN_DIRECT_ACCESS_REGWEN_RESVAL = 1'h 1;
  parameter logic [3:0] OTP_CTRL_DIRECT_ACCESS_CMD_RESVAL = 4'h 0;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_CMD_RD_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_CMD_WR_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_CMD_DIGEST_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_DIRECT_ACCESS_CMD_ZEROIZE_RESVAL = 1'h 0;
  parameter logic [31:0] OTP_CTRL_DIRECT_ACCESS_RDATA_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_DIRECT_ACCESS_RDATA_0_DIRECT_ACCESS_RDATA_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_DIRECT_ACCESS_RDATA_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_DIRECT_ACCESS_RDATA_1_DIRECT_ACCESS_RDATA_1_RESVAL = 32'h 0;
  parameter logic [1:0] OTP_CTRL_CHECK_TRIGGER_RESVAL = 2'h 0;
  parameter logic [0:0] OTP_CTRL_CHECK_TRIGGER_INTEGRITY_RESVAL = 1'h 0;
  parameter logic [0:0] OTP_CTRL_CHECK_TRIGGER_CONSISTENCY_RESVAL = 1'h 0;
  parameter logic [31:0] OTP_CTRL_VENDOR_TEST_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_VENDOR_TEST_DIGEST_0_VENDOR_TEST_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_VENDOR_TEST_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_VENDOR_TEST_DIGEST_1_VENDOR_TEST_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_0_CREATOR_SW_CFG_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_CREATOR_SW_CFG_DIGEST_1_CREATOR_SW_CFG_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_0_OWNER_SW_CFG_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_OWNER_SW_CFG_DIGEST_1_OWNER_SW_CFG_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_0_ROT_CREATOR_IDENTITY_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_1_ROT_CREATOR_IDENTITY_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0_ROT_OWNER_AUTH_SLOT0_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1_ROT_OWNER_AUTH_SLOT0_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0_ROT_OWNER_AUTH_SLOT1_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1_ROT_OWNER_AUTH_SLOT1_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_0_ROT_OWNER_AUTH_SLOT2_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_1_ROT_OWNER_AUTH_SLOT2_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_0_ROT_OWNER_AUTH_SLOT3_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_1_ROT_OWNER_AUTH_SLOT3_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_0_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_1_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_0_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_1_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_0_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_1_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_0_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_0_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0]
      OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_1_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_1_RESVAL =
      32'h 0;
  parameter logic [31:0] OTP_CTRL_ROM_PATCH_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_ROM_PATCH_DIGEST_0_ROM_PATCH_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_ROM_PATCH_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_ROM_PATCH_DIGEST_1_ROM_PATCH_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_CP_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_CP_DIGEST_0_SOC_FUSES_CP_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_CP_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_CP_DIGEST_1_SOC_FUSES_CP_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_FT_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_FT_DIGEST_0_SOC_FUSES_FT_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_FT_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SOC_FUSES_FT_DIGEST_1_SOC_FUSES_FT_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG0_DIGEST_0_HW_CFG0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG0_DIGEST_1_HW_CFG0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG1_DIGEST_0_HW_CFG1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG1_DIGEST_1_HW_CFG1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG2_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG2_DIGEST_0_HW_CFG2_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG2_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_HW_CFG2_DIGEST_1_HW_CFG2_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET0_DIGEST_0_SECRET0_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET0_DIGEST_1_SECRET0_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET1_DIGEST_0_SECRET1_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET1_DIGEST_1_SECRET1_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET2_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET2_DIGEST_0_SECRET2_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET2_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET2_DIGEST_1_SECRET2_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET3_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET3_DIGEST_0_SECRET3_DIGEST_0_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET3_DIGEST_1_RESVAL = 32'h 0;
  parameter logic [31:0] OTP_CTRL_SECRET3_DIGEST_1_SECRET3_DIGEST_1_RESVAL = 32'h 0;

  // Window parameters for core interface
  parameter logic [CoreAw-1:0] OTP_CTRL_SW_CFG_WINDOW_OFFSET = 13'h 1000;
  parameter int unsigned       OTP_CTRL_SW_CFG_WINDOW_SIZE   = 'h 1000;
  parameter int unsigned       OTP_CTRL_SW_CFG_WINDOW_IDX    = 0;

  // Register index for core interface
  typedef enum int {
    OTP_CTRL_INTR_STATE,
    OTP_CTRL_INTR_ENABLE,
    OTP_CTRL_INTR_TEST,
    OTP_CTRL_ALERT_TEST,
    OTP_CTRL_STATUS,
    OTP_CTRL_PARTITION_STATUS_0,
    OTP_CTRL_ERR_CODE_0,
    OTP_CTRL_ERR_CODE_1,
    OTP_CTRL_ERR_CODE_2,
    OTP_CTRL_ERR_CODE_3,
    OTP_CTRL_ERR_CODE_4,
    OTP_CTRL_ERR_CODE_5,
    OTP_CTRL_ERR_CODE_6,
    OTP_CTRL_ERR_CODE_7,
    OTP_CTRL_ERR_CODE_8,
    OTP_CTRL_ERR_CODE_9,
    OTP_CTRL_ERR_CODE_10,
    OTP_CTRL_ERR_CODE_11,
    OTP_CTRL_ERR_CODE_12,
    OTP_CTRL_ERR_CODE_13,
    OTP_CTRL_ERR_CODE_14,
    OTP_CTRL_ERR_CODE_15,
    OTP_CTRL_ERR_CODE_16,
    OTP_CTRL_ERR_CODE_17,
    OTP_CTRL_ERR_CODE_18,
    OTP_CTRL_ERR_CODE_19,
    OTP_CTRL_ERR_CODE_20,
    OTP_CTRL_ERR_CODE_21,
    OTP_CTRL_ERR_CODE_22,
    OTP_CTRL_ERR_CODE_23,
    OTP_CTRL_ERR_CODE_24,
    OTP_CTRL_ERR_CODE_25,
    OTP_CTRL_ERR_CODE_26,
    OTP_CTRL_ERR_CODE_27,
    OTP_CTRL_DIRECT_ACCESS_REGWEN,
    OTP_CTRL_DIRECT_ACCESS_CMD,
    OTP_CTRL_DIRECT_ACCESS_ADDRESS,
    OTP_CTRL_DIRECT_ACCESS_WDATA_0,
    OTP_CTRL_DIRECT_ACCESS_WDATA_1,
    OTP_CTRL_DIRECT_ACCESS_RDATA_0,
    OTP_CTRL_DIRECT_ACCESS_RDATA_1,
    OTP_CTRL_CHECK_TRIGGER_REGWEN,
    OTP_CTRL_CHECK_TRIGGER,
    OTP_CTRL_CHECK_REGWEN,
    OTP_CTRL_CHECK_TIMEOUT,
    OTP_CTRL_INTEGRITY_CHECK_PERIOD,
    OTP_CTRL_CONSISTENCY_CHECK_PERIOD,
    OTP_CTRL_VENDOR_TEST_READ_LOCK,
    OTP_CTRL_CREATOR_SW_CFG_READ_LOCK,
    OTP_CTRL_OWNER_SW_CFG_READ_LOCK,
    OTP_CTRL_OWNERSHIP_SLOT_STATE_READ_LOCK,
    OTP_CTRL_ROT_CREATOR_IDENTITY_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT0_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT1_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT2_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT3_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_READ_LOCK,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_READ_LOCK,
    OTP_CTRL_EXT_NVM_READ_LOCK,
    OTP_CTRL_ROM_PATCH_READ_LOCK,
    OTP_CTRL_SOC_FUSES_CP_READ_LOCK,
    OTP_CTRL_SOC_FUSES_FT_READ_LOCK,
    OTP_CTRL_SCRATCH_FUSES_READ_LOCK,
    OTP_CTRL_VENDOR_TEST_DIGEST_0,
    OTP_CTRL_VENDOR_TEST_DIGEST_1,
    OTP_CTRL_CREATOR_SW_CFG_DIGEST_0,
    OTP_CTRL_CREATOR_SW_CFG_DIGEST_1,
    OTP_CTRL_OWNER_SW_CFG_DIGEST_0,
    OTP_CTRL_OWNER_SW_CFG_DIGEST_1,
    OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_0,
    OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_1,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_0,
    OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_1,
    OTP_CTRL_ROM_PATCH_DIGEST_0,
    OTP_CTRL_ROM_PATCH_DIGEST_1,
    OTP_CTRL_SOC_FUSES_CP_DIGEST_0,
    OTP_CTRL_SOC_FUSES_CP_DIGEST_1,
    OTP_CTRL_SOC_FUSES_FT_DIGEST_0,
    OTP_CTRL_SOC_FUSES_FT_DIGEST_1,
    OTP_CTRL_HW_CFG0_DIGEST_0,
    OTP_CTRL_HW_CFG0_DIGEST_1,
    OTP_CTRL_HW_CFG1_DIGEST_0,
    OTP_CTRL_HW_CFG1_DIGEST_1,
    OTP_CTRL_HW_CFG2_DIGEST_0,
    OTP_CTRL_HW_CFG2_DIGEST_1,
    OTP_CTRL_SECRET0_DIGEST_0,
    OTP_CTRL_SECRET0_DIGEST_1,
    OTP_CTRL_SECRET1_DIGEST_0,
    OTP_CTRL_SECRET1_DIGEST_1,
    OTP_CTRL_SECRET2_DIGEST_0,
    OTP_CTRL_SECRET2_DIGEST_1,
    OTP_CTRL_SECRET3_DIGEST_0,
    OTP_CTRL_SECRET3_DIGEST_1
  } otp_ctrl_core_id_e;

  // Register width information to check illegal writes for core interface
  parameter logic [3:0] OTP_CTRL_CORE_PERMIT [109] = '{
    4'b 0001, // index[  0] OTP_CTRL_INTR_STATE
    4'b 0001, // index[  1] OTP_CTRL_INTR_ENABLE
    4'b 0001, // index[  2] OTP_CTRL_INTR_TEST
    4'b 0001, // index[  3] OTP_CTRL_ALERT_TEST
    4'b 0011, // index[  4] OTP_CTRL_STATUS
    4'b 1111, // index[  5] OTP_CTRL_PARTITION_STATUS_0
    4'b 0001, // index[  6] OTP_CTRL_ERR_CODE_0
    4'b 0001, // index[  7] OTP_CTRL_ERR_CODE_1
    4'b 0001, // index[  8] OTP_CTRL_ERR_CODE_2
    4'b 0001, // index[  9] OTP_CTRL_ERR_CODE_3
    4'b 0001, // index[ 10] OTP_CTRL_ERR_CODE_4
    4'b 0001, // index[ 11] OTP_CTRL_ERR_CODE_5
    4'b 0001, // index[ 12] OTP_CTRL_ERR_CODE_6
    4'b 0001, // index[ 13] OTP_CTRL_ERR_CODE_7
    4'b 0001, // index[ 14] OTP_CTRL_ERR_CODE_8
    4'b 0001, // index[ 15] OTP_CTRL_ERR_CODE_9
    4'b 0001, // index[ 16] OTP_CTRL_ERR_CODE_10
    4'b 0001, // index[ 17] OTP_CTRL_ERR_CODE_11
    4'b 0001, // index[ 18] OTP_CTRL_ERR_CODE_12
    4'b 0001, // index[ 19] OTP_CTRL_ERR_CODE_13
    4'b 0001, // index[ 20] OTP_CTRL_ERR_CODE_14
    4'b 0001, // index[ 21] OTP_CTRL_ERR_CODE_15
    4'b 0001, // index[ 22] OTP_CTRL_ERR_CODE_16
    4'b 0001, // index[ 23] OTP_CTRL_ERR_CODE_17
    4'b 0001, // index[ 24] OTP_CTRL_ERR_CODE_18
    4'b 0001, // index[ 25] OTP_CTRL_ERR_CODE_19
    4'b 0001, // index[ 26] OTP_CTRL_ERR_CODE_20
    4'b 0001, // index[ 27] OTP_CTRL_ERR_CODE_21
    4'b 0001, // index[ 28] OTP_CTRL_ERR_CODE_22
    4'b 0001, // index[ 29] OTP_CTRL_ERR_CODE_23
    4'b 0001, // index[ 30] OTP_CTRL_ERR_CODE_24
    4'b 0001, // index[ 31] OTP_CTRL_ERR_CODE_25
    4'b 0001, // index[ 32] OTP_CTRL_ERR_CODE_26
    4'b 0001, // index[ 33] OTP_CTRL_ERR_CODE_27
    4'b 0001, // index[ 34] OTP_CTRL_DIRECT_ACCESS_REGWEN
    4'b 0001, // index[ 35] OTP_CTRL_DIRECT_ACCESS_CMD
    4'b 0011, // index[ 36] OTP_CTRL_DIRECT_ACCESS_ADDRESS
    4'b 1111, // index[ 37] OTP_CTRL_DIRECT_ACCESS_WDATA_0
    4'b 1111, // index[ 38] OTP_CTRL_DIRECT_ACCESS_WDATA_1
    4'b 1111, // index[ 39] OTP_CTRL_DIRECT_ACCESS_RDATA_0
    4'b 1111, // index[ 40] OTP_CTRL_DIRECT_ACCESS_RDATA_1
    4'b 0001, // index[ 41] OTP_CTRL_CHECK_TRIGGER_REGWEN
    4'b 0001, // index[ 42] OTP_CTRL_CHECK_TRIGGER
    4'b 0001, // index[ 43] OTP_CTRL_CHECK_REGWEN
    4'b 1111, // index[ 44] OTP_CTRL_CHECK_TIMEOUT
    4'b 1111, // index[ 45] OTP_CTRL_INTEGRITY_CHECK_PERIOD
    4'b 1111, // index[ 46] OTP_CTRL_CONSISTENCY_CHECK_PERIOD
    4'b 0001, // index[ 47] OTP_CTRL_VENDOR_TEST_READ_LOCK
    4'b 0001, // index[ 48] OTP_CTRL_CREATOR_SW_CFG_READ_LOCK
    4'b 0001, // index[ 49] OTP_CTRL_OWNER_SW_CFG_READ_LOCK
    4'b 0001, // index[ 50] OTP_CTRL_OWNERSHIP_SLOT_STATE_READ_LOCK
    4'b 0001, // index[ 51] OTP_CTRL_ROT_CREATOR_IDENTITY_READ_LOCK
    4'b 0001, // index[ 52] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_READ_LOCK
    4'b 0001, // index[ 53] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_READ_LOCK
    4'b 0001, // index[ 54] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_READ_LOCK
    4'b 0001, // index[ 55] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_READ_LOCK
    4'b 0001, // index[ 56] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_READ_LOCK
    4'b 0001, // index[ 57] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_READ_LOCK
    4'b 0001, // index[ 58] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_READ_LOCK
    4'b 0001, // index[ 59] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_READ_LOCK
    4'b 0001, // index[ 60] OTP_CTRL_EXT_NVM_READ_LOCK
    4'b 0001, // index[ 61] OTP_CTRL_ROM_PATCH_READ_LOCK
    4'b 0001, // index[ 62] OTP_CTRL_SOC_FUSES_CP_READ_LOCK
    4'b 0001, // index[ 63] OTP_CTRL_SOC_FUSES_FT_READ_LOCK
    4'b 0001, // index[ 64] OTP_CTRL_SCRATCH_FUSES_READ_LOCK
    4'b 1111, // index[ 65] OTP_CTRL_VENDOR_TEST_DIGEST_0
    4'b 1111, // index[ 66] OTP_CTRL_VENDOR_TEST_DIGEST_1
    4'b 1111, // index[ 67] OTP_CTRL_CREATOR_SW_CFG_DIGEST_0
    4'b 1111, // index[ 68] OTP_CTRL_CREATOR_SW_CFG_DIGEST_1
    4'b 1111, // index[ 69] OTP_CTRL_OWNER_SW_CFG_DIGEST_0
    4'b 1111, // index[ 70] OTP_CTRL_OWNER_SW_CFG_DIGEST_1
    4'b 1111, // index[ 71] OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_0
    4'b 1111, // index[ 72] OTP_CTRL_ROT_CREATOR_IDENTITY_DIGEST_1
    4'b 1111, // index[ 73] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_0
    4'b 1111, // index[ 74] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_DIGEST_1
    4'b 1111, // index[ 75] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_0
    4'b 1111, // index[ 76] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_DIGEST_1
    4'b 1111, // index[ 77] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_0
    4'b 1111, // index[ 78] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_DIGEST_1
    4'b 1111, // index[ 79] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_0
    4'b 1111, // index[ 80] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_DIGEST_1
    4'b 1111, // index[ 81] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_0
    4'b 1111, // index[ 82] OTP_CTRL_ROT_OWNER_AUTH_SLOT0_STATE_DIGEST_1
    4'b 1111, // index[ 83] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_0
    4'b 1111, // index[ 84] OTP_CTRL_ROT_OWNER_AUTH_SLOT1_STATE_DIGEST_1
    4'b 1111, // index[ 85] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_0
    4'b 1111, // index[ 86] OTP_CTRL_ROT_OWNER_AUTH_SLOT2_STATE_DIGEST_1
    4'b 1111, // index[ 87] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_0
    4'b 1111, // index[ 88] OTP_CTRL_ROT_OWNER_AUTH_SLOT3_STATE_DIGEST_1
    4'b 1111, // index[ 89] OTP_CTRL_ROM_PATCH_DIGEST_0
    4'b 1111, // index[ 90] OTP_CTRL_ROM_PATCH_DIGEST_1
    4'b 1111, // index[ 91] OTP_CTRL_SOC_FUSES_CP_DIGEST_0
    4'b 1111, // index[ 92] OTP_CTRL_SOC_FUSES_CP_DIGEST_1
    4'b 1111, // index[ 93] OTP_CTRL_SOC_FUSES_FT_DIGEST_0
    4'b 1111, // index[ 94] OTP_CTRL_SOC_FUSES_FT_DIGEST_1
    4'b 1111, // index[ 95] OTP_CTRL_HW_CFG0_DIGEST_0
    4'b 1111, // index[ 96] OTP_CTRL_HW_CFG0_DIGEST_1
    4'b 1111, // index[ 97] OTP_CTRL_HW_CFG1_DIGEST_0
    4'b 1111, // index[ 98] OTP_CTRL_HW_CFG1_DIGEST_1
    4'b 1111, // index[ 99] OTP_CTRL_HW_CFG2_DIGEST_0
    4'b 1111, // index[100] OTP_CTRL_HW_CFG2_DIGEST_1
    4'b 1111, // index[101] OTP_CTRL_SECRET0_DIGEST_0
    4'b 1111, // index[102] OTP_CTRL_SECRET0_DIGEST_1
    4'b 1111, // index[103] OTP_CTRL_SECRET1_DIGEST_0
    4'b 1111, // index[104] OTP_CTRL_SECRET1_DIGEST_1
    4'b 1111, // index[105] OTP_CTRL_SECRET2_DIGEST_0
    4'b 1111, // index[106] OTP_CTRL_SECRET2_DIGEST_1
    4'b 1111, // index[107] OTP_CTRL_SECRET3_DIGEST_0
    4'b 1111  // index[108] OTP_CTRL_SECRET3_DIGEST_1
  };

endpackage
