# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event_name == 'pull_request_target')
        uses: pavona/cla-assistant@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Token grants access to store signatures in remote repository.
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT_TOKEN }}
        with:
          path-to-signatures: signatures.json
          # Path to CLA document.
          path-to-document: https://github.com/pavona/pavona/blob/main/CLA-Individual
          branch: main

          # GitHub organization name of the repository that stores the signatures.
          remote-organization-name: pavona
          # Remote repository that stores the signatures.
          remote-repository-name: cla-signatures
          # Pull request comment containing instructions for signing the CLA.
          custom-notsigned-prcomment: |
            Welcome to the Pavona Project! Before your contribution can be merged, the Pavona Project Foundation requires you to sign the Contributor License Agreement (CLA). Note that all CLAs are based on those from Apache.

            If you are contributing on behalf of your employer and they are a member of GlobalPlatform, no further action is required and your contribution can be accepted for review. Please reach out to your employer for any questions regarding the GlobalPlatform IPR.

            If your employer is _not_ a member of GlobalPlatform, please have an authorized party of your organization complete, sign and submit the [CLA-Corporate](https://github.com/pavona/pavona/blob/main/CLA-Corporate) on their behalf.

            If you are an independent contributor, please complete, sign and submit the [CLA-Individual](https://github.com/pavona/pavona/blob/main/CLA-Individual).

            To submit your CLA, e-mail it along your GitHub username(s), to secretariat@globalplatform.org. If your company is a member of GlobalPlatform, or has already completed a Corporate CLA, please email secretariat@globalplatform.org _from your corporate email address_ with your GitHub username to properly associate your GitHub account with your company. Please reference the Pavona Project Foundation in your email.

            Once the executed CLA has been received, the project will be able to merge your contribution upon its review and acceptance.
          # 'pull request comment when all contributors has signed, defaults to **CLA Assistant Lite bot** All Contributors have signed the CLA.'
          custom-allsigned-prcomment: 'All committers have signed the CLA.<br/>'
